version: "2"
services:
  app:
    container_name: veciapp-server
    restart: always
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "443:443"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes_from:
      - mongodata
  mongodata:
    image: tianon/true
    volumes:
      - /data/db
